import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <>
      <Head>
        <title>Ecommattic</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/assets/favicon.png' />
      </Head>

       {/* Masthead*/}
      <header id="header" className="fixed-top d-flex align-items-center">
        <div className="container d-flex align-items-center justify-content-between">
          <div className="logo">
            <a href="/"> <img  src="/assets/img/ecommattic.png" alt="Ecommattic"></img></a>
          </div>
          {/* Navigation*/}
          <nav id="navbar" className="navbar">
            <ul>
              <li><a className="nav-link scrollto active" href="#hero">Home</a></li>
              <li><a className="nav-link scrollto" href="#about">About</a></li>
              <li><a className="nav-link scrollto" href="#services">Services</a></li>
              <li><a className="nav-link scrollto" href="#contact">Contact</a></li>
            </ul>
            <i className="bi bi-list mobile-nav-toggle"></i>
          </nav>
        </div>
      </header>
    
      {/* Hero Section*/}
      <section id="hero" className="d-flex align-items-center">
        <div className="container">
          <div className="row">
            <div className="col-lg-6 pt-5 pt-lg-0 order-2 order-lg-1 d-flex flex-column justify-content-center">
              <h1>Elevating Ecommerce & Custom Software Solutions</h1>
              <h2>As a software development company, our primary objective is to empower businesses through top-notch solutions</h2>
            </div>
            <div className="col-lg-6 order-1 order-lg-2 hero-img">
              <Image className="img-fluid animated"
                    src="/assets/img/hero-img.png" alt="Hero section"
                    width={500}
                    height={300} />
        
            </div>
          </div>
        </div>
      </section>
      {/* Main Section*/}
      <main id="main">
        <section id="about" className="about">
          <div className="container">

            <div className="section-title" data-aos="fade-up">
              <h2>About Us</h2>
            </div>

            <div className="row content">
              
              <div className="col-lg-6 pt-4 pt-lg-0" data-aos="fade-up" data-aos-delay="300">
                  <p>
                  We specialize in providing comprehensive e-commerce and custom software solutions. 
                  Our primary goal is to enhance the shopping experience for e-commerce stores and assist startups in building their brand from the scratch. 
                  With expertise in developing web and mobile applications,we deliver tailored solutions to meet the unique requirements of our clients.
                  <br></br>
                  Whether you need a seamless e-commerce platform, a user-friendly mobile application, or customized software tailored to your specific needs, Ecommattic is here to transform your business and propel it to new heights. Partner with us and unlock the true potential of your online presence.</p>
                </div>

              <div className="col-lg-6" data-aos="fade-up" data-aos-delay="150">
                <p>
                Clients choose us as their software company for several compelling reasons
                </p>
                <ul>
                  <li><i className="ri-check-double-line"></i> Expertise</li>
                  <li><i className="ri-check-double-line"></i> Customization</li>
                  <li><i className="ri-check-double-line"></i> Quality and Reliability</li>
                  <li><i className="ri-check-double-line"></i> Collaboration</li>
                  <li><i className="ri-check-double-line"></i> Start-up Support</li>
                  <li><i className="ri-check-double-line"></i> Customer Satisfaction</li>
                </ul>
              </div>
           
            </div>

          </div>
        </section>

        <section id="services" className="services">
          <div className="container">

            <div className="section-title" data-aos="fade-up">
              <h2>Services</h2>
              <p>Our software development services deliver customized solutions that precisely cater to your target audience</p>
            </div>

            <div className="row">
              
              <div className="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0">
                <div className="icon-box" data-aos="fade-up" data-aos-delay="100">
                  <div className="icon"><i className="bi bi-shop"></i></div>
                  <h4 className="title">Ecommerce Development</h4>
                  <p className="description">Our services aid in business growth by strategically targeting and reaching potential customers</p>
                </div>
              </div>

              <div className="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0">
                <div className="icon-box" data-aos="fade-up" data-aos-delay="200">
                  <div className="icon"><i className="bi bi-grid"></i></div>
                  <h4 className="title">Web Applications</h4>
                  <p className="description">Create impactful products with sophisticated interfaces and enjoyable user experiences</p>
                </div>
              </div>

              <div className="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0">
                <div className="icon-box" data-aos="fade-up" data-aos-delay="300">
                  <div className="icon"><i className="bi bi-phone-flip"></i></div>
                  <h4 className="title">Mobile Applications</h4>
                  <p className="description">Count on our expertise to deliver impactful mobile applications from ideation to design to development</p>
                </div>
              </div>

              <div className="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0">
                <div className="icon-box" data-aos="fade-up" data-aos-delay="400">
                  <div className="icon"><i className="bi bi-sliders2-vertical"></i></div>
                  <h4 className="title">Custom Softwares</h4>
                  <p className="description">Streamline your business operations with our tailored solutions and seamless integration capabilities</p>
                </div>
              </div>

            </div>

          </div>
        </section>

        <section id="contact" className="contact">
          <div className="container">

            <div className="section-title" data-aos="fade-up">
              <h2>Contact Us</h2>
            </div>

            <div className="row">

              <div className="col-lg-4 col-md-6" data-aos="fade-up" data-aos-delay="100">
                <div className="contact-about">
                  <h3>Ecommattic</h3>
                  <p>We are dedicated to delivering excellent customer service and ensuring a prompt response to your inquiries. Whether you have questions about our services, pricing, or any other aspect, we are here to help. Don't hesitate to reach out to us – we look forward to hearing from you! <br></br> Follow Us </p>
                  <div className="social-links">
                    <a href="#" className="twitter"><i className="bi bi-twitter"></i></a>
                    <a href="#" className="facebook"><i className="bi bi-facebook"></i></a>
                    <a href="#" className="instagram"><i className="bi bi-instagram"></i></a>
                    <a href="#" className="linkedin"><i className="bi bi-linkedin"></i></a>
                  </div>
                </div>
              </div>

              <div className="col-lg-3 col-md-6 mt-4 mt-md-0" data-aos="fade-up" data-aos-delay="200">
                <div className="info">
                  <div>
                    <i className="ri-map-pin-line"></i>
                    <p>Islamabad, Pakistan</p>
                  </div>

                  <div>
                    <i className="ri-mail-send-line"></i>
                    <p>ecommattic@gmail.com</p>
                  </div>

                  {/* <div>
                    <i className="ri-phone-line"></i>
                    <p>+1 5589 55488 55s</p>
                  </div> */}

                </div>
              </div>

              <div className="col-lg-5 col-md-12" data-aos="fade-up" data-aos-delay="300">
                <form action="forms" method="post" role="form" className="php-email-form">
                  <div className="form-group">
                    <input type="text" name="name" className="form-control" id="name" placeholder="Your Name" required />
                  </div>
                  <div className="form-group">
                    <input type="email" className="form-control" name="email" id="email" placeholder="Your Email" required />
                  </div>
                  <div className="form-group">
                    <input type="text" className="form-control" name="subject" id="subject" placeholder="Subject" required />
                  </div>
                  <div className="form-group">
                    <textarea className="form-control" name="message" rows="5" placeholder="Message" required></textarea>
                  </div>
                  <div className="my-3">
                    <div className="loading">Loading</div>
                    <div className="error-message"></div>
                    <div className="sent-message">Your message has been sent. Thank you!</div>
                  </div>
                  <div className="text-center"><button type="submit">Send Message</button></div>
                </form>
              </div>

            </div>

          </div>
        </section>
      </main>

      {/* Footer Section*/}
      <footer id="footer">
        <div className="container">
          <div className="row d-flex align-items-center">
            <div className="col-lg-6 text-lg-left text-center">
              <div className="copyright">
                &copy; Copyright <strong>Ecommattic</strong>. All Rights Reserved
              </div>
            </div>
            <div className="col-lg-6">
              <nav className="footer-links text-lg-right text-center pt-2 pt-lg-0">
                <a href="#hero" className="scrollto">Home</a>
                <a href="#about" className="scrollto">About</a>
                <a href="/privacy">Privacy Policy</a>
              </nav>
            </div>
          </div>
        </div>
      </footer>
      <a href="#" className="back-to-top d-flex align-items-center justify-content-center"><i className="bi bi-arrow-up-short"></i></a>
  
  </>
  )
}
